import swaggerJsdoc from 'swagger-jsdoc';

const options: swaggerJsdoc.Options = {
  definition: {
    openapi: '3.0.3',
    info: {
      title: 'MeteorEdit API',
      version: '1.0.0',
      description: 'API publique de MeteorEdit — Plateforme OSINT de gestion d\'investigations',
    },
    servers: [
      {
        url: 'http://localhost:3001',
        description: 'Serveur de développement',
      },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
          description: 'Token JWT obtenu via /api/auth/login',
        },
      },
      schemas: {
        Error: {
          type: 'object',
          properties: {
            message: { type: 'string' },
          },
        },
        User: {
          type: 'object',
          properties: {
            _id: { type: 'string' },
            email: { type: 'string', format: 'email' },
            firstName: { type: 'string' },
            lastName: { type: 'string' },
            role: { type: 'string', enum: ['admin', 'user'] },
            isActive: { type: 'boolean' },
            avatarPath: { type: 'string', nullable: true },
            twoFactorEnabled: { type: 'boolean' },
            preferences: { type: 'object' },
            signature: {
              type: 'object',
              properties: {
                title: { type: 'string' },
                name: { type: 'string' },
                service: { type: 'string' },
                unit: { type: 'string' },
                email: { type: 'string' },
              },
            },
            signatureImagePath: { type: 'string', nullable: true },
            lastLoginAt: { type: 'string', format: 'date-time', nullable: true },
            lastLoginIp: { type: 'string', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Entity: {
          type: 'object',
          properties: {
            name: { type: 'string' },
            type: { type: 'string' },
            description: { type: 'string' },
          },
          required: ['name', 'type'],
        },
        Investigator: {
          type: 'object',
          properties: {
            name: { type: 'string' },
            service: { type: 'string' },
            unit: { type: 'string' },
            phone: { type: 'string' },
            email: { type: 'string' },
          },
        },
        Dossier: {
          type: 'object',
          properties: {
            _id: { type: 'string' },
            title: { type: 'string' },
            description: { type: 'string' },
            status: { type: 'string', enum: ['open', 'in_progress', 'closed'] },
            icon: { type: 'string', nullable: true },
            logoPath: { type: 'string', nullable: true },
            objectives: { type: 'string' },
            entities: { type: 'array', items: { $ref: '#/components/schemas/Entity' } },
            judicialFacts: { type: 'string' },
            tags: { type: 'array', items: { type: 'string' } },
            investigator: { $ref: '#/components/schemas/Investigator' },
            owner: { type: 'string' },
            collaborators: { type: 'array', items: { type: 'string' } },
            isEncrypted: { type: 'boolean' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        DossierNode: {
          type: 'object',
          properties: {
            _id: { type: 'string' },
            dossierId: { type: 'string' },
            parentId: { type: 'string', nullable: true },
            type: { type: 'string', enum: ['folder', 'note', 'mindmap', 'document', 'map', 'dataset'] },
            title: { type: 'string' },
            order: { type: 'number' },
            content: { type: 'object', nullable: true },
            contentText: { type: 'string', nullable: true },
            excalidrawData: { type: 'object', nullable: true },
            mapData: { type: 'object', nullable: true },
            fileUrl: { type: 'string', nullable: true },
            fileName: { type: 'string', nullable: true },
            fileSize: { type: 'number', nullable: true },
            deletedAt: { type: 'string', format: 'date-time', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Snapshot: {
          type: 'object',
          properties: {
            _id: { type: 'string' },
            nodeId: { type: 'string' },
            dossierId: { type: 'string' },
            type: { type: 'string', enum: ['note', 'mindmap'] },
            content: { type: 'object' },
            label: { type: 'string' },
            createdAt: { type: 'string', format: 'date-time' },
          },
        },
        Comment: {
          type: 'object',
          properties: {
            _id: { type: 'string' },
            nodeId: { type: 'string' },
            userId: {
              type: 'object',
              properties: {
                _id: { type: 'string' },
                firstName: { type: 'string' },
                lastName: { type: 'string' },
                avatarPath: { type: 'string', nullable: true },
              },
            },
            content: { type: 'string' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Task: {
          type: 'object',
          properties: {
            _id: { type: 'string' },
            dossierId: { type: 'string' },
            title: { type: 'string' },
            description: { type: 'string' },
            status: { type: 'string', enum: ['todo', 'in_progress', 'done'] },
            priority: { type: 'string', enum: ['low', 'medium', 'high'] },
            assigneeId: { type: 'string', nullable: true },
            createdBy: { type: 'string' },
            dueDate: { type: 'string', format: 'date-time', nullable: true },
            completedAt: { type: 'string', format: 'date-time', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        NoteTemplate: {
          type: 'object',
          properties: {
            _id: { type: 'string' },
            title: { type: 'string' },
            description: { type: 'string' },
            content: { type: 'object', nullable: true },
            owner: { type: 'string' },
            isShared: { type: 'boolean' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        ReportTemplate: {
          type: 'object',
          properties: {
            _id: { type: 'string' },
            title: { type: 'string' },
            description: { type: 'string' },
            prompt: { type: 'string' },
            owner: { type: 'string' },
            isDefault: { type: 'boolean' },
            isShared: { type: 'boolean' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        SiteSettings: {
          type: 'object',
          properties: {
            appName: { type: 'string' },
            logoPath: { type: 'string', nullable: true },
            accentColor: { type: 'string' },
            faviconPath: { type: 'string', nullable: true },
            loginMessage: { type: 'string' },
            loginBackgroundPath: { type: 'string', nullable: true },
            require2FA: { type: 'boolean' },
            maintenanceMode: { type: 'boolean' },
            maintenanceMessage: { type: 'string' },
            registrationEnabled: { type: 'boolean' },
            sessionTimeoutMinutes: { type: 'number' },
            passwordMinLength: { type: 'number' },
            passwordRequireUppercase: { type: 'boolean' },
            passwordRequireNumber: { type: 'boolean' },
            passwordRequireSpecial: { type: 'boolean' },
            maxLoginAttempts: { type: 'number' },
            lockoutDurationMinutes: { type: 'number' },
          },
        },
        ActivityLog: {
          type: 'object',
          properties: {
            _id: { type: 'string' },
            userId: { type: 'string' },
            action: { type: 'string' },
            targetType: { type: 'string', enum: ['dossier', 'user', 'system', 'node'] },
            targetId: { type: 'string', nullable: true },
            metadata: { type: 'object' },
            ip: { type: 'string' },
            userAgent: { type: 'string' },
            timestamp: { type: 'string', format: 'date-time' },
          },
        },
        Notification: {
          type: 'object',
          properties: {
            _id: { type: 'string' },
            userId: { type: 'string' },
            type: { type: 'string', enum: ['collaborator.added', 'collaborator.removed', 'dossier.updated', 'node.updated', 'mention', 'task.assigned'] },
            message: { type: 'string' },
            dossierId: { type: 'string', nullable: true },
            fromUserId: { type: 'string', nullable: true },
            read: { type: 'boolean' },
            createdAt: { type: 'string', format: 'date-time' },
          },
        },
        PluginSettings: {
          type: 'object',
          properties: {
            mapbox: {
              type: 'object',
              properties: {
                apiKey: { type: 'string' },
                defaultStyle: { type: 'string' },
                defaultCenter: { type: 'array', items: { type: 'number' } },
                defaultZoom: { type: 'number' },
              },
            },
            ollama: {
              type: 'object',
              properties: {
                baseUrl: { type: 'string' },
                selectedModel: { type: 'string' },
                enabled: { type: 'boolean' },
                reportPrompt: { type: 'string' },
              },
            },
          },
        },
      },
    },
    tags: [
      { name: 'Auth', description: 'Authentification et gestion de compte' },
      { name: 'Profile', description: 'Profil utilisateur, avatar et signature' },
      { name: '2FA', description: 'Authentification a deux facteurs' },
      { name: 'Dossiers', description: 'Gestion des dossiers d\'investigation' },
      { name: 'Nodes', description: 'Noeuds hierarchiques (notes, mindmaps, documents, etc.)' },
      { name: 'Comments', description: 'Commentaires sur les noeuds' },
      { name: 'Snapshots', description: 'Historique de versions des noeuds' },
      { name: 'Tasks', description: 'Taches liees aux dossiers' },
      { name: 'Templates', description: 'Modeles de notes avec placeholders' },
      { name: 'ReportTemplates', description: 'Modeles de prompts pour rapports IA' },
      { name: 'Export', description: 'Export de dossiers' },
      { name: 'Search', description: 'Recherche globale' },
      { name: 'AI', description: 'Fonctionnalites IA (Ollama)' },
      { name: 'Clipper', description: 'Web clipper pour capturer du contenu web' },
      { name: 'Notifications', description: 'Notifications utilisateur' },
      { name: 'Encryption', description: 'Chiffrement de bout en bout (E2E)' },
      { name: 'Admin', description: 'Administration (utilisateurs, parametres, audit)' },
      { name: 'Settings', description: 'Parametres publics du site' },
    ],
  },
  apis: ['./src/routes/*.ts'],
};

export const swaggerSpec = swaggerJsdoc(options);
